export const getVisualSupportConfig = (type, profileID) => {
  const configs = {
    "Task Analysis": { 
      title: "Create New Task Analyses",
      scratch: `/FromScratch/${profileID}`,
      temp: `/stepsupport/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
      type: "Task Analysis",
      defaultText: "Insert Task Name",
      errorMsg: "Please enter a task name",
      addMsg: "+ Add Step",
      stepTitle: "Step",
      showTime: true,
      label: "Task Step",
      showCategory: true,
    },
    "Daily Schedule": { 
      title: "Create New Daily Schedule",
      scratch: `/FromScratch/${profileID}`,
      temp: `/stepsupport/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
			type: "Daily Schedule",
      defaultText: "Insert Daily Schedule Name",
      errorMsg: "Please enter a name for this daily schedule",
      addMsg: "+ Add Task",
      stepTitle: "Task",
      showTime: false,
      label: "Task Title",
      showCategory: false,
    },
    "Weekly Calendar": { 
      title: "Create New Weekly Calendar",
      scratch: `/FromScratch/${profileID}`,
      temp: `/weeklycalendars/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
			type: "Weekly Calendar",
    },
    "Social Story": { 
      title: "Create New Social Story",
      scratch: `/FromScratch/${profileID}`,
      temp: `/stepsupport/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
      type: "Social Story",
      defaultText: "Insert Social Story Name",
      errorMsg: "Please enter a name for this social story",
      addMsg: "+ Add Story Point",
      stepTitle: "Story Point",
      showTime: false,
      label: "Story Point Description",
      showCategory: true,
    },
    "Environmental Support": { 
      title: "Create New Environment Support",
      scratch: `/FromScratch/${profileID}`,
      temp: `/stepsupport/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
      type: "Environmental Support",
      defaultText: "Insert Environmental Support Name",
      errorMsg: "Please enter a name for this environmental support",
      addMsg: "+ Add Environmental Support",
      stepTitle: "Environment Support",
      showTime: false,
      label: "Environmental Support Description",
      showCategory: true,
    },
    "Choice Board": { 
      title: "Create New Choice Board",
      scratch: `/FromScratch/${profileID}`,
      temp: `/stepsupport/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
      type: "Choice Board",
      defaultText: "Insert Choice Board Name",
      errorMsg: "Please enter a name for this choice board",
      addMsg: "+ Add Choice",
      stepTitle: "Choice",
      showTime: false,
      label: "Choice Name",
      showCategory: true,
    },
    "First-Then": { 
      title: "Create New First-Then",
      scratch: `/FromScratch/${profileID}`,
      temp: `/firstthen/${profileID}`,
      exist: `/choosepremadetemplate/${profileID}`,
      type: `First-Then`
    }
  };
  
  return configs[type] || null;
};